![](files/images/EscUpmPolit_p.gif "UPM")

## Imports

In [46]:
import pandas as pd
import csv
import numpy as np
import dask.dataframe as dd

## Reading data

In [47]:
#Path where the database is
path="dataset/train_balanced.csv"

#reading the database
df=dd.read_csv(path)
df.info()

<class 'dask.dataframe.core.DataFrame'>
Columns: 37 entries, Unnamed: 0 to pt_d
dtypes: object(1), int64(36)

In [48]:
df.columns

Index(['Unnamed: 0', 'label', 'uid', 'task_id', 'adv_id', 'creat_type_cd',
       'adv_prim_id', 'dev_id', 'inter_type_cd', 'slot_id', 'spread_app_id',
       'tags', 'app_first_class', 'app_second_class', 'age', 'city',
       'city_rank', 'device_name', 'device_size', 'career', 'gender',
       'net_type', 'residence', 'his_app_size', 'his_on_shelf_time',
       'app_score', 'emui_dev', 'list_time', 'device_price',
       'up_life_duration', 'up_membership_grade', 'membership_life_duration',
       'consume_purchase', 'communication_onlinerate',
       'communication_avgonline_30d', 'indu_name', 'pt_d'],
      dtype='object')

## Missing Values 

In [49]:
df.head()

Unnamed: 0  label      uid  task_id  adv_id  creat_type_cd  adv_prim_id  \
0           0      0  2078912     4265    2140              7          167   
1           1      0  1029564     4305    4663              7          156   
2           2      0  1952180     2229    5483              7          156   
3           3      0  2046795     3506    4867              2          142   
4           4      1  2013717     5879    3563              7          150   

   dev_id  inter_type_cd  slot_id  ...  list_time  device_price  \
0      37              5       11  ...          8             5   
1      56              5       21  ...         10             2   
2      56              5       13  ...          5             4   
3      36              5       12  ...         14             2   
4      17              5       16  ...          8             5   

   up_life_duration  up_membership_grade  membership_life_duration  \
0                20                    1                        -1   
1                16                   -1                        -1   
2                -1                   -1                        -1   
3                12                   -1                        -1   
4                -1                   -1                        -1   

   consume_purchase                           communication_onlinerate  \
0                 2  0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...   
1                 2  0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...   
2                 2  5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...   
3                 2  6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23   
4                 2  5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...   

   communication_avgonline_30d  indu_name  pt_d  
0                           13         17     6  
1                           13         17     5  
2                           11         17     2  
3                            7         42     6  
4                           11         36     2  

[5 rows x 37 columns]

In [50]:
df = df.drop(['Unnamed: 0','membership_life_duration','up_membership_grade','up_life_duration','his_on_shelf_time','his_app_size'],axis=1)

In [51]:
#df = df.drop(df[df.communication_avgonline_30d==-1].index)
#df = df.drop(df[df.device_price==-1].index)
#df = df.drop(df[df.list_time==-1].index)
#df = df.drop(df[df.age==-1].index)
df.head()

label      uid  task_id  adv_id  creat_type_cd  adv_prim_id  dev_id  \
0      0  2078912     4265    2140              7          167      37   
1      0  1029564     4305    4663              7          156      56   
2      0  1952180     2229    5483              7          156      56   
3      0  2046795     3506    4867              2          142      36   
4      1  2013717     5879    3563              7          150      17   

   inter_type_cd  slot_id  spread_app_id  ...  residence  app_score  emui_dev  \
0              5       11             44  ...         33          2        20   
1              5       21             58  ...         34          2        14   
2              5       13             58  ...         46          2        28   
3              5       12             80  ...         20          2        14   
4              5       16             11  ...         34          2        20   

   list_time  device_price  consume_purchase  \
0          8             5                 2   
1         10             2                 2   
2          5             4                 2   
3         14             2                 2   
4          8             5                 2   

                            communication_onlinerate  \
0  0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...   
1  0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...   
2  5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...   
3  6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23   
4  5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...   

   communication_avgonline_30d  indu_name  pt_d  
0                           13         17     6  
1                           13         17     5  
2                           11         17     2  
3                            7         42     6  
4                           11         36     2  

[5 rows x 31 columns]

In [52]:
df.columns

Index(['label', 'uid', 'task_id', 'adv_id', 'creat_type_cd', 'adv_prim_id',
       'dev_id', 'inter_type_cd', 'slot_id', 'spread_app_id', 'tags',
       'app_first_class', 'app_second_class', 'age', 'city', 'city_rank',
       'device_name', 'device_size', 'career', 'gender', 'net_type',
       'residence', 'app_score', 'emui_dev', 'list_time', 'device_price',
       'consume_purchase', 'communication_onlinerate',
       'communication_avgonline_30d', 'indu_name', 'pt_d'],
      dtype='object')

## Dummies

In [53]:
#comm = df['communication_onlinerate'].compute()
#comm=comm.apply(lambda x:x.split('^'))
#dummy=pd.get_dummies(comm.apply(pd.Series).stack()).sum(level=0)
#del comm
#df = df.drop('communication_onlinerate',axis=1)
#comm_dask = dd.from_pandas(dummy)
#df = dd.concat

In [54]:
df['communication_onlinerate'].head()

0    0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...
1    0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...
2    5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...
3    6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23
4    5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...
Name: communication_onlinerate, dtype: object

In [55]:
#dummy=pd.get_dummies(df['communication_onlinerate'].apply(pd.Series).stack()).sum(level=0)

In [56]:
categorical_columns = ['gender', 'city','city_rank', 'career', 'residence', 'device_name', 'task_id', 'adv_prim_id', 'dev_id', 'spread_app_id', 'tags','indu_name','adv_id','inter_type_cd', 'creat_type_cd']
df[categorical_columns] = df[categorical_columns].astype('category')
df[categorical_columns].head()

gender city city_rank career residence device_name task_id adv_prim_id  \
0      2  111         3      9        33          75    4265         167   
1      2   53         3      4        34          65    4305         156   
2      2   36         4      5        46          87    2229         156   
3      2  110         5      9        20          66    3506         142   
4      4 -114         4      4        34          75    5879         150   

  dev_id spread_app_id tags indu_name adv_id inter_type_cd creat_type_cd  
0     37            44   40        17   2140             5             7  
1     56            58   37        17   4663             5             7  
2     56            58   37        17   5483             5             7  
3     36            80   41        42   4867             5             2  
4     17            11   39        36   3563             5             7

In [57]:
df = dd.get_dummies(df.categorize(),columns=categorical_columns)
df.head()

label      uid  slot_id  app_first_class  app_second_class  age  \
0      0  2078912       11                4                25    7   
1      0  1029564       21                4                21    5   
2      0  1952180       13                4                21    3   
3      0  2046795       12                4                26    4   
4      1  2013717       16                4                17    6   

   device_size  net_type  app_score  emui_dev  ...  inter_type_cd_4  \
0          141         2          2        20  ...                0   
1          141         2          2        14  ...                0   
2          117         2          2        28  ...                0   
3          193         3          2        14  ...                0   
4          156         2          2        20  ...                0   

   inter_type_cd_5  creat_type_cd_2 creat_type_cd_3  creat_type_cd_4  \
0                1                0               0                0   
1                1                0               0                0   
2                1                0               0                0   
3                1                1               0                0   
4                1                0               0                0   

   creat_type_cd_5  creat_type_cd_6  creat_type_cd_7  creat_type_cd_8  \
0                0                0                1                0   
1                0                0                1                0   
2                0                0                1                0   
3                0                0                0                0   
4                0                0                1                0   

   creat_type_cd_9  
0                0  
1                0  
2                0  
3                0  
4                0  

[5 rows x 8890 columns]

In [60]:
df.columns

Index(['label', 'uid', 'slot_id', 'app_first_class', 'app_second_class', 'age',
       'device_size', 'net_type', 'app_score', 'emui_dev',
       ...
       'inter_type_cd_4', 'inter_type_cd_5', 'creat_type_cd_2',
       'creat_type_cd_3', 'creat_type_cd_4', 'creat_type_cd_5',
       'creat_type_cd_6', 'creat_type_cd_7', 'creat_type_cd_8',
       'creat_type_cd_9'],
      dtype='object', length=8890)

In [59]:
#df['communication_onlinerate']=df['communication_onlinerate'].apply(lambda x:x.split('^'))
#dummy=pd.get_dummies(df['communication_onlinerate'].apply(pd.Series).stack()).sum(level=0)
#df = pd.concat([df, dummy], axis=1)
#df = df.drop('communication_onlinerate',axis=1)
#df = df.drop('index',axis=1)
#df.head()

ValueError: Metadata inference failed in `apply`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
TypeError("unhashable type: 'list'")

Traceback:
---------
  File "C:\Users\jorge\Anaconda3\lib\site-packages\dask\dataframe\utils.py", line 168, in raise_on_meta_error
    yield
  File "C:\Users\jorge\Anaconda3\lib\site-packages\dask\dataframe\core.py", line 4725, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "C:\Users\jorge\Anaconda3\lib\site-packages\dask\utils.py", line 876, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "C:\Users\jorge\Anaconda3\lib\site-packages\pandas\core\series.py", line 4039, in apply
    mapped = self._values.map(f)
  File "C:\Users\jorge\Anaconda3\lib\site-packages\pandas\core\arrays\categorical.py", line 1254, in map
    self._codes.copy(), categories=new_categories, ordered=self.ordered
  File "C:\Users\jorge\Anaconda3\lib\site-packages\pandas\core\arrays\categorical.py", line 678, in from_codes
    categories=categories, ordered=ordered, dtype=dtype
  File "C:\Users\jorge\Anaconda3\lib\site-packages\pandas\core\dtypes\dtypes.py", line 335, in _from_values_or_dtype
    dtype = CategoricalDtype(categories, ordered)
  File "C:\Users\jorge\Anaconda3\lib\site-packages\pandas\core\dtypes\dtypes.py", line 226, in __init__
    self._finalize(categories, ordered, fastpath=False)
  File "C:\Users\jorge\Anaconda3\lib\site-packages\pandas\core\dtypes\dtypes.py", line 347, in _finalize
    categories = self.validate_categories(categories, fastpath=fastpath)
  File "C:\Users\jorge\Anaconda3\lib\site-packages\pandas\core\dtypes\dtypes.py", line 526, in validate_categories
    if not categories.is_unique:
  File "pandas\_libs\properties.pyx", line 34, in pandas._libs.properties.CachedProperty.__get__
  File "C:\Users\jorge\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 1808, in is_unique
    return self._engine.is_unique
  File "pandas\_libs\index.pyx", line 183, in pandas._libs.index.IndexEngine.is_unique.__get__
  File "pandas\_libs\index.pyx", line 190, in pandas._libs.index.IndexEngine._do_unique_check
  File "pandas\_libs\index.pyx", line 255, in pandas._libs.index.IndexEngine._ensure_mapping_populated
  File "pandas\_libs\index.pyx", line 263, in pandas._libs.index.IndexEngine._call_map_locations
  File "pandas\_libs\hashtable_class_helper.pxi", line 1640, in pandas._libs.hashtable.PyObjectHashTable.map_locations


## Bins 

In [61]:
#df['device_size_binned']=dd.cut(df['device_size'], 5,labels=False)
#df['emui_dev_binned']=dd.cut(df['emui_dev'], 5,labels=False)
#df['list_time_binned']=dd.cut(df['list_time'], 5,labels=False)


AttributeError: module 'dask.dataframe' has no attribute 'cut'

In [62]:
#df.device_size_binned.value_counts()

Dask Series Structure:
npartitions=1
    int64
      ...
Name: device_size, dtype: int64
Dask Name: value-counts-agg, 158 tasks

In [37]:
#df.emui_dev_binned.value_counts()

2    415
0    244
4     85
1     19
Name: emui_dev_binned, dtype: int64

In [38]:
#df.list_time_binned.value_counts()

1    265
3    210
0    161
2     76
4     51
Name: list_time_binned, dtype: int64

In [63]:
x = df.loc[:, df.columns != 'label']
y = df.loc[:, df.columns == 'label']
#y=np.array(y)

## Standard

In [40]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [41]:
scaler=MinMaxScaler()
scaler.fit(x)
x=scaler.transform(x)


## Classifier

In [42]:
c = df.corr().abs()["label"][:]
so = c.sort_values(kind="quicksort")
so.tail(20)

adv_prim_id_210     0.099385
dev_id_29           0.099544
spread_app_id_78    0.099686
residence_27        0.100069
indu_name_17        0.100505
spread_app_id_88    0.101468
career_9            0.103150
tags_23             0.103867
dev_id_70           0.104640
dev_id_60           0.104823
app_score           0.104823
app_first_class     0.106045
career_4            0.110159
inter_type_cd_3     0.114182
adv_prim_id_183     0.114746
spread_app_id_86    0.114972
tags_37             0.131331
slot_id             0.144627
label               1.000000
pt_d                     NaN
Name: label, dtype: float64

In [21]:
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, classification_report, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [21]:
k = 5
kf = KFold(n_splits=k)

'''
models = {"Logistic Regression":LogisticRegression(multi_class="auto", solver="lbfgs", max_iter=2000), \
          "Decision Tree": DecisionTreeClassifier(), \
          "Random Forest": RandomForestClassifier(n_estimators=100), \
          "Nearest Neighbors": KNeighborsClassifier(n_neighbors=5), \
          "Perceptron": MLPClassifier(max_iter=2000)}
'''

models = {"Logistic Regression":LogisticRegression(multi_class="auto", solver="lbfgs", max_iter=2000)}

for name in models:
    print("Start training models of {}".format(name))
    i = 0
    f1_global = []
    for train, test in kf.split(x):
        i+=1
        x_train, x_test, y_train, y_test = x[train], x[test], y[train], y[test]
        model = models[name].fit(x_train,y_train)
        y_out = model.predict(x_test)
        print("Log Loss",metrics.log_loss(y_test,LR.predict_proba(X_test)))
        # We have to provide the real value of the target and the model's output
        f1_global.append(f1_score(y_test, y_out, average="weighted"))
        print(confusion_matrix(y_test, y_out))
        print(classification_report(y_test, y_out))
    print("Global: f1={:.4f}\n".format(np.average(f1_global)))

Start training models of Logistic Regression


C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[7449   66]
 [  55 7290]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7515
           1       0.99      0.99      0.99      7345

    accuracy                           0.99     14860
   macro avg       0.99      0.99      0.99     14860
weighted avg       0.99      0.99      0.99     14860



C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[7401   58]
 [  50 7350]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7459
           1       0.99      0.99      0.99      7400

    accuracy                           0.99     14859
   macro avg       0.99      0.99      0.99     14859
weighted avg       0.99      0.99      0.99     14859



C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[7444   60]
 [  62 7293]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7504
           1       0.99      0.99      0.99      7355

    accuracy                           0.99     14859
   macro avg       0.99      0.99      0.99     14859
weighted avg       0.99      0.99      0.99     14859



C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


KeyboardInterrupt: 

4

In [48]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=1)

model = LogisticRegression(solver="lbfgs")

model.fit(x_train,y_train)

y_out=model.predict(x_test)
y_out_prob=model.predict_proba(x_test)

print(confusion_matrix(y_test, y_out))
print(classification_report(y_test, y_out))
print(metrics.log_loss(y_test,y_out_prob))
print(roc_auc_score(y_test,y_out))

C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[7328   73]
 [  66 7393]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7401
           1       0.99      0.99      0.99      7459

    accuracy                           0.99     14860
   macro avg       0.99      0.99      0.99     14860
weighted avg       0.99      0.99      0.99     14860

0.03644681438830902


NameError: name 'roc_auc' is not defined

In [49]:
y_test[0:20]

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1]], dtype=int64)

In [50]:
y_out_prob[0:20]

array([[6.92964500e-04, 9.99307036e-01],
       [8.23086637e-04, 9.99176913e-01],
       [9.95223018e-01, 4.77698203e-03],
       [4.30148791e-08, 9.99999957e-01],
       [5.22911659e-04, 9.99477088e-01],
       [4.11787122e-06, 9.99995882e-01],
       [7.23115143e-04, 9.99276885e-01],
       [9.50796033e-01, 4.92039671e-02],
       [1.15351151e-09, 9.99999999e-01],
       [5.30918665e-09, 9.99999995e-01],
       [6.30860735e-02, 9.36913927e-01],
       [2.24517390e-01, 7.75482610e-01],
       [3.05990252e-05, 9.99969401e-01],
       [1.82019561e-03, 9.98179804e-01],
       [5.05490225e-05, 9.99949451e-01],
       [9.99999796e-01, 2.04054973e-07],
       [9.06139579e-01, 9.38604210e-02],
       [9.99999981e-01, 1.89487344e-08],
       [9.96903002e-01, 3.09699821e-03],
       [1.22463986e-03, 9.98775360e-01]])

In [51]:
y_out[0:20]

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1],
      dtype=int64)