![](files/images/EscUpmPolit_p.gif "UPM")

## Imports

In [23]:
import pandas as pd
import csv
import numpy as np


## Reading data

In [24]:
#Path where the database is
path="dataset/train_data.csv"

#reading the database
df=pd.read_csv(path, delimiter='|',nrows=10000)
df_original=df.copy()
df

label      uid  task_id  adv_id  creat_type_cd  adv_prim_id  dev_id  \
0         0  1638254     2112    6869              7          207      17   
1         0  1161786     3104    3247              7          183      29   
2         0  1814783     5890    4183              7          178      17   
3         0  1468996     1993    5405              7          207      17   
4         0  2164010     5439    4677              2          138      24   
...     ...      ...      ...     ...            ...          ...     ...   
9995      0  1649201     5353    3537              7          177      60   
9996      0  1747511     1054    1325              7          147      29   
9997      0  1354003     4806    2176              7          206      64   
9998      0  1293303     1439    1070              7          156      56   
9999      0  2095849     5574    6776              7          207      17   

      inter_type_cd  slot_id  spread_app_id  tags  app_first_class  \
0                 5       11             13    37                4   
1                 5       17             86    37                4   
2                 5       11             70    39                4   
3                 5       21             13    37                4   
4                 5       12             33    15                4   
...             ...      ...            ...   ...              ...   
9995              5       17             31    40                2   
9996              5       17             86    37                4   
9997              5       12             22    39                4   
9998              5       21             58    37                4   
9999              5       13             13    37                4   

      app_second_class  age  city  city_rank  device_name  device_size  \
0                   21    5   437          5           37          162   
1                   21    4   370          5           59          141   
2                   17    5   306          3           81          162   
3                   21    5   275          5           88          180   
4                   15    5   412          3           88          180   
...                ...  ...   ...        ...          ...          ...   
9995                25    6   212          3           69          310   
9996                21    5   416          5           72          141   
9997                17    1   275          5           41          193   
9998                21    5   398          4           54          141   
9999                21    4   158          3           41          193   

      career  gender  net_type  residence  his_app_size  his_on_shelf_time  \
0          4       2         2         28             4                  2   
1          9       4         2         26             4                  3   
2          4       2         2         21             2                  3   
3          4       2         2         23             4                  2   
4          4       2         2         20            16                  3   
...      ...     ...       ...        ...           ...                ...   
9995       4       2         2         33            -1                 -1   
9996       4       2         2         12             4                  3   
9997       4       4         2         23             4                  3   
9998       9       2         2         34            14                  3   
9999       9       4         2         15             4                  2   

      app_score  emui_dev  list_time  device_price  up_life_duration  \
0             2        20          4             4                20   
1             2        20          4             4                18   
2             2        20          4             5                20   
3             2        20          7             3                -1   
4             2        20          7             3    

In [25]:
df.columns

Index(['label', 'uid', 'task_id', 'adv_id', 'creat_type_cd', 'adv_prim_id',
       'dev_id', 'inter_type_cd', 'slot_id', 'spread_app_id', 'tags',
       'app_first_class', 'app_second_class', 'age', 'city', 'city_rank',
       'device_name', 'device_size', 'career', 'gender', 'net_type',
       'residence', 'his_app_size', 'his_on_shelf_time', 'app_score',
       'emui_dev', 'list_time', 'device_price', 'up_life_duration',
       'up_membership_grade', 'membership_life_duration', 'consume_purchase',
       'communication_onlinerate', 'communication_avgonline_30d', 'indu_name',
       'pt_d'],
      dtype='object')

## Balance 

In [26]:
df1=df[df.label==1]
df0=df[df.label==0]
df0=df0.iloc[0:len(df1)]
df=df1.append(df0, ignore_index=True)
df=df.sample(frac=1)
df=df.reset_index()

## Number Values

In [27]:
for column in df:
    print(column )
    print(len(df[column].unique()))

index
772
label
2
uid
769
task_id
311
adv_id
313
creat_type_cd
8
adv_prim_id
63
dev_id
35
inter_type_cd
3
slot_id
11
spread_app_id
48
tags
24
app_first_class
3
app_second_class
16
age
8
city
217
city_rank
4
device_name
60
device_size
23
career
9
gender
3
net_type
3
residence
32
his_app_size
18
his_on_shelf_time
4
app_score
2
emui_dev
11
list_time
15
device_price
6
up_life_duration
14
up_membership_grade
4
membership_life_duration
3
consume_purchase
7
communication_onlinerate
27
communication_avgonline_30d
13
indu_name
28
pt_d
1


## Missing Values 

In [28]:
df.shape

(772, 37)

In [29]:
nullvalues=(df==-1).sum(axis=0).sort_values(ascending=False)
nullvalues.head(10)

membership_life_duration       767
up_membership_grade            688
up_life_duration               261
his_on_shelf_time              119
his_app_size                   119
age                              9
communication_avgonline_30d      9
device_price                     9
list_time                        9
dev_id                           0
dtype: int64

In [30]:
df.drop(['membership_life_duration','up_membership_grade','up_life_duration','his_on_shelf_time','his_app_size'],axis=1,inplace=True)

In [31]:
df.drop(df[df.communication_avgonline_30d==-1].index,inplace=True)
df.drop(df[df.device_price==-1].index,inplace=True)
df.drop(df[df.list_time==-1].index,inplace=True)
df.drop(df[df.age==-1].index,inplace=True)

In [32]:
df.shape

(763, 32)

## Dummies

In [33]:
df = pd.get_dummies(df, columns=['gender'])
df = pd.get_dummies(df, columns=['city'])
df = pd.get_dummies(df, columns=['career'])
df = pd.get_dummies(df, columns=['residence'])
df = pd.get_dummies(df, columns=['device_name'])
df = pd.get_dummies(df, columns=['task_id'])
df = pd.get_dummies(df, columns=['adv_prim_id'])
df = pd.get_dummies(df, columns=['dev_id'])
df = pd.get_dummies(df, columns=['spread_app_id'])
df = pd.get_dummies(df, columns=['tags'])
df = pd.get_dummies(df, columns=['indu_name'])
df = pd.get_dummies(df, columns=['adv_id'])
df = pd.get_dummies(df, columns=['inter_type_cd'])
df = pd.get_dummies(df, columns=['creat_type_cd'])
pd.set_option('display.max_columns', None)
df

index  label      uid  slot_id  app_first_class  app_second_class  age  \
0      371      1  1589245       12                4                25    7   
1      764      0  2100840       11                4                21    5   
2      215      1  1375490       12                4                17    1   
3      461      0  1189740       17                4                25    1   
4      285      1  1110915       13                4                21    7   
..     ...    ...      ...      ...              ...               ...  ...   
767     98      1  1528714       12                4                21    5   
768    488      0  1524124       22                2                23    5   
769    662      0  1822627       12                4                17    7   
770    123      1  1205892       17                2                21    4   
771    562      0  1591733       12                4                25    5   

     city_rank  device_size  net_type  app_score  emui_dev  list_time  \
0            3          193         2          2        14         13   
1            3          141         2          2        20          8   
2            5          193         2          2        17         14   
3            4          193         2          2        17         14   
4            3          141         2          2        20         10   
..         ...          ...       ...        ...       ...        ...   
767          4          141         2          2        14         10   
768          3          288         2          1        20          8   
769          3          117         2          2        20          9   
770          3          141         2          1        27         14   
771          5          117         2          2        14          9   

     device_price  consume_purchase  \
0               2                 2   
1               5                 2   
2               4                 2   
3               4                 2   
4               2                 2   
..            ...               ...   
767             2                 5   
768             5                 2   
769             3                 2   
770             5                 2   
771             3                 5   

                              communication_onlinerate  \
0    0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...   
1      7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23   
2    4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^2...   
3                        14^15^16^17^18^19^20^21^22^23   
4    5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...   
..                                                 ...   
767  6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23   
768  0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...   
769                                        20^21^22^23   
770  0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...   
771  0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...   

     communication_avgonline_30d  pt_d  gender_2  gender_3  gender_4  \
0                             13     1         1         0         0   
1                             10     1         1         0         0   
2                             12     1         1         0         0   
3                              6     1         0         1         0   
4                             11     1         1         0         0   
..                           ...   ...       ...       ...       ...   
767                           10     1         0         0         1   
768                           13     1         1         0         0   
769                            5     1         1         0         0   
770                           13     1         1         0         0   
771                           13     1         0         0         1   

     city_101  city_102  city_103  city_104  city_105  city_107  city_108  \
0           0         0         0         0         0         0        

In [34]:
df['communication_onlinerate']=df['communication_onlinerate'].apply(lambda x:x.split('^'))
dummy=pd.get_dummies(df['communication_onlinerate'].apply(pd.Series).stack()).sum(level=0)
df = pd.concat([df, dummy], axis=1)
df = df.drop('communication_onlinerate',axis=1)
df = df.drop('index',axis=1)
df.head()

label      uid  slot_id  app_first_class  app_second_class  age  city_rank  \
0      1  1589245       12                4                25    7          3   
1      0  2100840       11                4                21    5          3   
2      1  1375490       12                4                17    1          5   
3      0  1189740       17                4                25    1          4   
4      1  1110915       13                4                21    7          3   

   device_size  net_type  app_score  emui_dev  list_time  device_price  \
0          193         2          2        14         13             2   
1          141         2          2        20          8             5   
2          193         2          2        17         14             4   
3          193         2          2        17         14             4   
4          141         2          2        20         10             2   

   consume_purchase  communication_avgonline_30d  pt_d  gender_2  gender_3  \
0                 2                           13     1         1         0   
1                 2                           10     1         1         0   
2                 2                           12     1         1         0   
3                 2                            6     1         0         1   
4                 2                           11     1         1         0   

   gender_4  city_101  city_102  city_103  city_104  city_105  city_107  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0         0         0         0   
4         0         0         0         0         0         0         0   

   city_108  city_109  city_110  city_112  city_114  city_118  city_119  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0         0         0         0   
4         0         0         0         0         0         0         0   

   city_121  city_124  city_126  city_128  city_129  city_131  city_132  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0         0         0         1   
4         0         0         0         0         0         0         0   

   city_133  city_134  city_135  city_136  city_138  city_140  city_141  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0         0         0         0   
4         0         0         0         0         1         0         0   

   city_142  city_145  city_146  city_149  city_152  city_153  city_154  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0         0         0         0   
4         0         0         0         0         0         0         0   

   city_155  city_156  city_157  city_158  city_159  city_160  city_163  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0      

## Bins 

In [35]:
df['device_size_binned']=pd.cut(df['device_size'], 5,labels=False)
df['emui_dev_binned']=pd.cut(df['emui_dev'], 5,labels=False)
df['list_time_binned']=pd.cut(df['list_time'], 5,labels=False)


In [36]:
df.device_size_binned.value_counts()

0    491
1    216
4     37
3     10
2      9
Name: device_size_binned, dtype: int64

In [37]:
df.emui_dev_binned.value_counts()

2    415
0    244
4     85
1     19
Name: emui_dev_binned, dtype: int64

In [38]:
df.list_time_binned.value_counts()

1    265
3    210
0    161
2     76
4     51
Name: list_time_binned, dtype: int64

In [39]:
x = df.loc[:, df.columns != 'label']
y = df.loc[:, df.columns == 'label']
y=np.array(y)

## Standard

In [40]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [41]:
scaler=MinMaxScaler()
scaler.fit(x)
x=scaler.transform(x)


## Classifier

In [42]:
c = df.corr().abs()["label"][:]
so = c.sort_values(kind="quicksort")
so.tail(20)

adv_prim_id_210     0.099385
dev_id_29           0.099544
spread_app_id_78    0.099686
residence_27        0.100069
indu_name_17        0.100505
spread_app_id_88    0.101468
career_9            0.103150
tags_23             0.103867
dev_id_70           0.104640
dev_id_60           0.104823
app_score           0.104823
app_first_class     0.106045
career_4            0.110159
inter_type_cd_3     0.114182
adv_prim_id_183     0.114746
spread_app_id_86    0.114972
tags_37             0.131331
slot_id             0.144627
label               1.000000
pt_d                     NaN
Name: label, dtype: float64

In [21]:
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, classification_report, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [21]:
k = 5
kf = KFold(n_splits=k)

'''
models = {"Logistic Regression":LogisticRegression(multi_class="auto", solver="lbfgs", max_iter=2000), \
          "Decision Tree": DecisionTreeClassifier(), \
          "Random Forest": RandomForestClassifier(n_estimators=100), \
          "Nearest Neighbors": KNeighborsClassifier(n_neighbors=5), \
          "Perceptron": MLPClassifier(max_iter=2000)}
'''

models = {"Logistic Regression":LogisticRegression(multi_class="auto", solver="lbfgs", max_iter=2000)}

for name in models:
    print("Start training models of {}".format(name))
    i = 0
    f1_global = []
    for train, test in kf.split(x):
        i+=1
        x_train, x_test, y_train, y_test = x[train], x[test], y[train], y[test]
        model = models[name].fit(x_train,y_train)
        y_out = model.predict(x_test)
        print("Log Loss",metrics.log_loss(y_test,LR.predict_proba(X_test)))
        # We have to provide the real value of the target and the model's output
        f1_global.append(f1_score(y_test, y_out, average="weighted"))
        print(confusion_matrix(y_test, y_out))
        print(classification_report(y_test, y_out))
    print("Global: f1={:.4f}\n".format(np.average(f1_global)))

Start training models of Logistic Regression


C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[7449   66]
 [  55 7290]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7515
           1       0.99      0.99      0.99      7345

    accuracy                           0.99     14860
   macro avg       0.99      0.99      0.99     14860
weighted avg       0.99      0.99      0.99     14860



C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[7401   58]
 [  50 7350]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7459
           1       0.99      0.99      0.99      7400

    accuracy                           0.99     14859
   macro avg       0.99      0.99      0.99     14859
weighted avg       0.99      0.99      0.99     14859



C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[7444   60]
 [  62 7293]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7504
           1       0.99      0.99      0.99      7355

    accuracy                           0.99     14859
   macro avg       0.99      0.99      0.99     14859
weighted avg       0.99      0.99      0.99     14859



C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


KeyboardInterrupt: 

4

In [48]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=1)

model = LogisticRegression(solver="lbfgs")

model.fit(x_train,y_train)

y_out=model.predict(x_test)
y_out_prob=model.predict_proba(x_test)

print(confusion_matrix(y_test, y_out))
print(classification_report(y_test, y_out))
print(metrics.log_loss(y_test,y_out_prob))
print(roc_auc_score(y_test,y_out))

C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[7328   73]
 [  66 7393]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7401
           1       0.99      0.99      0.99      7459

    accuracy                           0.99     14860
   macro avg       0.99      0.99      0.99     14860
weighted avg       0.99      0.99      0.99     14860

0.03644681438830902


NameError: name 'roc_auc' is not defined

In [49]:
y_test[0:20]

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1]], dtype=int64)

In [50]:
y_out_prob[0:20]

array([[6.92964500e-04, 9.99307036e-01],
       [8.23086637e-04, 9.99176913e-01],
       [9.95223018e-01, 4.77698203e-03],
       [4.30148791e-08, 9.99999957e-01],
       [5.22911659e-04, 9.99477088e-01],
       [4.11787122e-06, 9.99995882e-01],
       [7.23115143e-04, 9.99276885e-01],
       [9.50796033e-01, 4.92039671e-02],
       [1.15351151e-09, 9.99999999e-01],
       [5.30918665e-09, 9.99999995e-01],
       [6.30860735e-02, 9.36913927e-01],
       [2.24517390e-01, 7.75482610e-01],
       [3.05990252e-05, 9.99969401e-01],
       [1.82019561e-03, 9.98179804e-01],
       [5.05490225e-05, 9.99949451e-01],
       [9.99999796e-01, 2.04054973e-07],
       [9.06139579e-01, 9.38604210e-02],
       [9.99999981e-01, 1.89487344e-08],
       [9.96903002e-01, 3.09699821e-03],
       [1.22463986e-03, 9.98775360e-01]])

In [51]:
y_out[0:20]

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1],
      dtype=int64)