![](files/images/EscUpmPolit_p.gif "UPM")

## Imports

In [ ]:
import pandas as pd
import csv
import numpy as np


## Reading data

In [ ]:
#Path where the database is
path="../../dataset/train_data.csv"

#reading the database
df=pd.read_csv(path, delimiter='|',nrows=10000)
df_original=df.copy()
df

In [ ]:
df.columns

## Balance 

In [ ]:
df1=df[df.label==1]
df0=df[df.label==0]
df0=df0.iloc[0:len(df1)]
df=df1.append(df0, ignore_index=True)
df=df.sample(frac=1)
df=df.reset_index()

## Number Values

In [ ]:
for column in df:
    print(column )
    print(len(df[column].unique()))

## Missing Values 

In [ ]:
df.shape

In [ ]:
nullvalues=(df==-1).sum(axis=0).sort_values(ascending=False)
nullvalues.head(10)

In [ ]:
df.drop(['membership_life_duration','up_membership_grade','up_life_duration','his_on_shelf_time','his_app_size'],axis=1,inplace=True)

In [ ]:
df.drop(df[df.communication_avgonline_30d==-1].index,inplace=True)
df.drop(df[df.device_price==-1].index,inplace=True)
df.drop(df[df.list_time==-1].index,inplace=True)
df.drop(df[df.age==-1].index,inplace=True)

In [ ]:
df.shape

## Dummies

In [ ]:
df = pd.get_dummies(df, columns=['gender'])
df = pd.get_dummies(df, columns=['city'])
df = pd.get_dummies(df, columns=['career'])
df = pd.get_dummies(df, columns=['residence'])
df = pd.get_dummies(df, columns=['device_name'])
df = pd.get_dummies(df, columns=['task_id'])
df = pd.get_dummies(df, columns=['adv_prim_id'])
df = pd.get_dummies(df, columns=['dev_id'])
df = pd.get_dummies(df, columns=['spread_app_id'])
df = pd.get_dummies(df, columns=['tags'])
df = pd.get_dummies(df, columns=['indu_name'])
df = pd.get_dummies(df, columns=['adv_id'])
df = pd.get_dummies(df, columns=['inter_type_cd'])
df = pd.get_dummies(df, columns=['creat_type_cd'])
pd.set_option('display.max_columns', None)
df

In [ ]:
df['communication_onlinerate']=df['communication_onlinerate'].apply(lambda x:x.split('^'))
dummy=pd.get_dummies(df['communication_onlinerate'].apply(pd.Series).stack()).sum(level=0)
df = pd.concat([df, dummy], axis=1)
df = df.drop('communication_onlinerate',axis=1)
df.head()

## Bins 

In [13]:
df['device_size_binned']=pd.cut(df['device_size'], 5,labels=False)
df['emui_dev_binned']=pd.cut(df['emui_dev'], 5,labels=False)
df['list_time_binned']=pd.cut(df['list_time'], 5,labels=False)


In [14]:
df.device_size_binned.value_counts()

0    48625
1    19548
4     3799
3     1594
2      730
Name: device_size_binned, dtype: int64

In [15]:
df.emui_dev_binned.value_counts()

2    40119
0    22089
4    10233
1     1855
Name: emui_dev_binned, dtype: int64

In [16]:
df.list_time_binned.value_counts()

2    29033
3    17742
1    14974
4    12546
0        1
Name: list_time_binned, dtype: int64

In [17]:
x = df.loc[:, df.columns != 'label']
y = df.loc[:, df.columns == 'label']
y=np.array(y)

In [19]:
x

index      uid  slot_id  app_first_class  app_second_class  age  \
0      16990  1737480       17                4                26    5   
1      11254  1296723       16                4                17    6   
2      63644  1666235       12                4                25    5   
3      64257  1594748       12                4                21    7   
4      65538  1600450       22                2                23    4   
...      ...      ...      ...              ...               ...  ...   
74967  10904  1024835       15                4                25    6   
74968  73079  1406724       11                2                26    5   
74969  34829  1005046       17                4                25    5   
74970  40524  2068532       12                4                25    2   
74971  50977  1721833       12                4                21    7   

       city_rank  device_size  net_type  app_score  emui_dev  list_time  \
0              5          162         3          2        14          4   
1              3          141         2          2        20          8   
2              4          141         2          2        12          9   
3              4          117         2          2        20          9   
4              5          287         4          1        20          4   
...          ...          ...       ...        ...       ...        ...   
74967          5          180         2          2        20          7   
74968          5          141         2          1        20         14   
74969          3          141         2          2        27         14   
74970          3          141         2          2        20          9   
74971          5          156         2          2        20          9   

       device_price  consume_purchase  communication_avgonline_30d  pt_d  \
0                 4                 5                           13     1   
1                 5                 2                           13     1   
2                 3                 2                           12     1   
3                 3                 2                           12     1   
4                 5                 2                           11     1   
...             ...               ...                          ...   ...   
74967             3                 2                           13     1   
74968             5                 2                           11     1   
74969             5                 2                           10     1   
74970             3                 2                           12     1   
74971             3                 5                           12     1   

       gender_2  gender_3  gender_4  city_101  city_102  city_103  city_104  \
0             1         0         0         0         0         0         0   
1             1         0         0         0         0         0         0   
2             1         0         0         0         0         0         0   
3             1         0         0         0         0         0         0   
4             1         0         0         0         0         0         0   
...         ...       ...       ...       ...       ...       ...       ...   
74967         0         0         1         0         0         0         0   
74968         0         0         1         0         0         0         0   
74969         1         0         0         0         0         0         0   
74970         0         0         1         0         0         0         0   
74971         1         0         0         0         0         0         0   

       city_105  city_106  city_107  city_108  city_109  city_110  city_111  \
0             0         0         0         0         0         0         0   
1             0         0         0         0         0         0         0   
2             0         0         0         0         0         0         0   
3             0         0         0    

In [20]:
y

array([[1],
       [1],
       [0],
       ...,
       [1],
       [0],
       [0]], dtype=int64)

In [ ]:
c = df.corr().abs()["label"][:]
so = c.sort_values(kind="quicksort")
so.tail(20)

## Standard

In [18]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

ImportError: DLL load failed: No se encontró el proceso especificado.

In [ ]:
scaler=MinMaxScaler()
scaler.fit(x)
x=scaler.transform(x)


## Classifier

In [25]:
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, classification_report, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [21]:
k = 5
kf = KFold(n_splits=k)

'''
models = {"Logistic Regression":LogisticRegression(multi_class="auto", solver="lbfgs", max_iter=2000), \
          "Decision Tree": DecisionTreeClassifier(), \
          "Random Forest": RandomForestClassifier(n_estimators=100), \
          "Nearest Neighbors": KNeighborsClassifier(n_neighbors=5), \
          "Perceptron": MLPClassifier(max_iter=2000)}
'''

models = {"Logistic Regression":LogisticRegression(multi_class="auto", solver="lbfgs", max_iter=2000)}

for name in models:
    print("Start training models of {}".format(name))
    i = 0
    f1_global = []
    for train, test in kf.split(x):
        i+=1
        x_train, x_test, y_train, y_test = x[train], x[test], y[train], y[test]
        model = models[name].fit(x_train,y_train)
        y_out = model.predict(x_test)
        print("Log Loss",metrics.log_loss(y_test,LR.predict_proba(X_test)))
        # We have to provide the real value of the target and the model's output
        f1_global.append(f1_score(y_test, y_out, average="weighted"))
        print(confusion_matrix(y_test, y_out))
        print(classification_report(y_test, y_out))
    print("Global: f1={:.4f}\n".format(np.average(f1_global)))

Start training models of Logistic Regression


C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[7449   66]
 [  55 7290]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7515
           1       0.99      0.99      0.99      7345

    accuracy                           0.99     14860
   macro avg       0.99      0.99      0.99     14860
weighted avg       0.99      0.99      0.99     14860



C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[7401   58]
 [  50 7350]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7459
           1       0.99      0.99      0.99      7400

    accuracy                           0.99     14859
   macro avg       0.99      0.99      0.99     14859
weighted avg       0.99      0.99      0.99     14859



C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[7444   60]
 [  62 7293]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7504
           1       0.99      0.99      0.99      7355

    accuracy                           0.99     14859
   macro avg       0.99      0.99      0.99     14859
weighted avg       0.99      0.99      0.99     14859



C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


KeyboardInterrupt: 

4

In [48]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=1)

model = LogisticRegression(solver="lbfgs")

model.fit(x_train,y_train)

y_out=model.predict(x_test)
y_out_prob=model.predict_proba(x_test)

print(confusion_matrix(y_test, y_out))
print(classification_report(y_test, y_out))
print(metrics.log_loss(y_test,y_out_prob))
print(roc_auc_score(y_test,y_out))

C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Marta Castiella\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[7328   73]
 [  66 7393]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7401
           1       0.99      0.99      0.99      7459

    accuracy                           0.99     14860
   macro avg       0.99      0.99      0.99     14860
weighted avg       0.99      0.99      0.99     14860

0.03644681438830902


NameError: name 'roc_auc' is not defined

In [49]:
y_test[0:20]

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1]], dtype=int64)

In [50]:
y_out_prob[0:20]

array([[6.92964500e-04, 9.99307036e-01],
       [8.23086637e-04, 9.99176913e-01],
       [9.95223018e-01, 4.77698203e-03],
       [4.30148791e-08, 9.99999957e-01],
       [5.22911659e-04, 9.99477088e-01],
       [4.11787122e-06, 9.99995882e-01],
       [7.23115143e-04, 9.99276885e-01],
       [9.50796033e-01, 4.92039671e-02],
       [1.15351151e-09, 9.99999999e-01],
       [5.30918665e-09, 9.99999995e-01],
       [6.30860735e-02, 9.36913927e-01],
       [2.24517390e-01, 7.75482610e-01],
       [3.05990252e-05, 9.99969401e-01],
       [1.82019561e-03, 9.98179804e-01],
       [5.05490225e-05, 9.99949451e-01],
       [9.99999796e-01, 2.04054973e-07],
       [9.06139579e-01, 9.38604210e-02],
       [9.99999981e-01, 1.89487344e-08],
       [9.96903002e-01, 3.09699821e-03],
       [1.22463986e-03, 9.98775360e-01]])

In [51]:
y_out[0:20]

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1],
      dtype=int64)